__author__ = 'Akanksha verma'

URL = 'https://www.facebook.com/'
title = 'Facebook – log in or sign up'
validusername = 'provide your valid user'
validpassword  = 'provide your valid password'
Invalidusername = 'ak'
Invalidpassword = '12345678'
timeout = '3s'
screenshot_path = '/home/akanksha/PycharmProjects/New_robot_framework_project/result'
